CREATE DATABASE DataWarehouse;
GO
USE master;

IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'DataWarehouse')
BEGIN
    ALTER DATABASE DataWarehouse SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DataWarehouse;
END;
GO

CREATE DATABASE DataWarehouse;

USE DataWarehouse;
GO

CREATE SCHEMA bronze AUTHORIZATION dbo;
GO

CREATE SCHEMA silver AUTHORIZATION dbo;
GO

CREATE SCHEMA gold AUTHORIZATION dbo;
GO